version: '3'

services:
  mysqldb:
    image: "mysql:5.6"
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=gestionfoyer
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"


  #backendapp

  app_achat_backend:
    image: ghammam:latest
    container_name: ghammam-devops
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/gestionfoyer
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
