version: '3'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: gestionfoyer
    ports:
      - "3306:3306"


  #backendapp

  app_achat_backend:
    image: ghammam:latest
    container_name: ghammam-devops
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
